gpt:
  authorization: "Authorization"
  bearer: "Bearer"
  apikey: "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"
  model: "gpt-4"
  max-tokens: 3000
  temperature: 0.7
  top-p: 1.0
  media-type: "application/json; charset=UTF-8"
  url: "https://api.openai.com/v1//completions"
  organization: "OpenAI-Organization"
  organization-value: "org-wzJHgPv7WSbsXQO3AuCYYCat"

webclient:
  gpt:
    authorization: "Authorization"
    bearer: "Bearer"
    apikey: "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"
    model: "gpt-4"
    max-tokens: 3000
    temperature: 0.7
    top-p: 1.0
    media-type: "application/json; charset=UTF-8"
    url: "https://api.openai.com/v1/chat/completions"
    organization: "OpenAI-Organization"
    organization-value: "org-wzJHgPv7WSbsXQO3AuCYYCat"

logging:
  level:
    root: error

server:
  port: 18080