webclient:
  gpt:
    authorization: "Authorization"
    bearer: "Bearer"
    apikey: "apikey value"
    model: "gpt-3.5-turbo"
    max-tokens: 3000
    temperature: 0.7
    top-p: 1.0
    media-type: "application/json; charset=UTF-8"
    url: "https://api.openai.com/v1/chat/completions"
    organization: "OpenAI-Organization"
    organization-value: "organization value"

logging:
  level:
    root: info

server:
  port: 18080